name: PlanetScale (Sleepercell / Sleepless Ping)
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Sleeper Cell / Sleepless Ping (Database)
        run: |
          curl --request PUT \
            --header 'authorization: ${{ secrets.AUTHORIZATION }}' \
            --url '${{ secrets.SITE_URL }}/api/sleepercell'